import { createApp } from "vue";
import ArcoVue from "@arco-design/web-vue";
import App from "./App.vue";
import NewSession from "./NewSession.vue";
import SessionDetail from "./SessionDetail.vue";
import HypothesisDetail from "./HypothesisDetail.vue";
import KnowledgeIntake from "./KnowledgeIntake.vue";
import KnowledgeBatchDetail from "./KnowledgeBatchDetail.vue";
import FinalReport from "./FinalReport.vue";
import EvidenceGraph from "./EvidenceGraph.vue";
import AgentOutputs from "./AgentOutputs.vue";
import EvidenceInterpretation from "./EvidenceInterpretation.vue";
import ValidationPlanDetail from "./ValidationPlanDetail.vue";
import RiskReviewDetail from "./RiskReviewDetail.vue";
import RouteRevisionGraph from "./RouteRevisionGraph.vue";
import "@arco-design/web-vue/dist/arco.css";
import "./styles.css";

const pathname = window.location.pathname;
const isHypothesisDetail = /^\/sessions\/[^/]+\/hypotheses\/[^/]+$/.test(pathname);
const isSessionDetail = /^\/sessions\/[^/]+$/.test(pathname);
const isKnowledgeBatchDetail = /^\/knowledge\/batches\/[^/]+$/.test(pathname);
const isFinalReport = /^\/sessions\/[^/]+\/overview$/.test(pathname);
const isEvidenceGraph = /^\/sessions\/[^/]+\/evidence-graph$/.test(pathname);
const isHypothesisEvidenceGraph = /^\/sessions\/[^/]+\/hypotheses\/[^/]+\/evidence-subgraph$/.test(pathname);
const isAgentOutputs = /^\/sessions\/[^/]+\/agent-outputs$/.test(pathname);
const isEvidenceInterpretation = /^\/sessions\/[^/]+\/artifacts\/artifacts\/[^/]+\/evidence\/package_[^/]+\.json$/.test(pathname);
const isValidationPlanDetail = /^\/sessions\/[^/]+\/artifacts\/artifacts\/[^/]+\/validation\/plan_[^/]+\.json$/.test(pathname);
const isRiskReviewDetail = /^\/sessions\/[^/]+\/artifacts\/artifacts\/[^/]+\/reviews\/(?:rev|review)_[^/]+\.json$/.test(pathname);
const isRouteRevisionGraph = /^\/sessions\/[^/]+\/(?:hypotheses\/[^/]+\/)?route-revision-graph$/.test(pathname);
const Root = pathname === "/sessions/new" ? NewSession : pathname === "/knowledge" ? KnowledgeIntake : isKnowledgeBatchDetail ? KnowledgeBatchDetail : isEvidenceInterpretation ? EvidenceInterpretation : isValidationPlanDetail ? ValidationPlanDetail : isRiskReviewDetail ? RiskReviewDetail : (isEvidenceGraph || isHypothesisEvidenceGraph) ? EvidenceGraph : isFinalReport ? FinalReport : isAgentOutputs ? AgentOutputs : isRouteRevisionGraph ? RouteRevisionGraph : isHypothesisDetail ? HypothesisDetail : isSessionDetail ? SessionDetail : App;
createApp(Root).use(ArcoVue).mount("#app");
